{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-publish/0.0.3/test-publish-0.0.3.module",
    "group": "cn.rtast.kmvnrepo",
    "module": "test-publish",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "test-publish-jvm-0.0.3.jar",
          "url": "test-publish-jvm-0.0.3.jar",
          "size": 898,
          "sha512": "504c38ee203b993f12dd3280c7fb400f47588e9f5c17d6aa97df8cd9bb9a416abc9e1735ba5eeaef33fdae2bfdf75f303d27f6f6bf5debbada31659bf64f3a5c",
          "sha256": "f70a30bc4adbe6952fa677a9d95cb1f8c73ccbeff1a5c72d330dc8fe86b906d2",
          "sha1": "3765a3481b3315a02d1767f56dae8b3ec44680f7",
          "md5": "a6f19d26ecdf495d0a22994fd09d064e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "test-publish-jvm-0.0.3.jar",
          "url": "test-publish-jvm-0.0.3.jar",
          "size": 898,
          "sha512": "504c38ee203b993f12dd3280c7fb400f47588e9f5c17d6aa97df8cd9bb9a416abc9e1735ba5eeaef33fdae2bfdf75f303d27f6f6bf5debbada31659bf64f3a5c",
          "sha256": "f70a30bc4adbe6952fa677a9d95cb1f8c73ccbeff1a5c72d330dc8fe86b906d2",
          "sha1": "3765a3481b3315a02d1767f56dae8b3ec44680f7",
          "md5": "a6f19d26ecdf495d0a22994fd09d064e"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-publish-jvm-0.0.3-sources.jar",
          "url": "test-publish-jvm-0.0.3-sources.jar",
          "size": 732,
          "sha512": "9aa4f139d0772973aa300c07a30655432e5c9822e0a9c7ead82441ca250be2c340b5aa7de203918a18db36092005ebe98b4961dc9d1d1e67d16eab95733794b3",
          "sha256": "c8c2bd42def53fbce3d593754acae20e876720c78d22739180fe2eab06375179",
          "sha1": "32f4399c0736653f36a759576fafc37342a458f1",
          "md5": "d96628c64e5df1af9bc80536fd5446e2"
        }
      ]
    }
  ]
}
