{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-publish/0.0.1/test-publish-0.0.1.module",
    "group": "cn.rtast.kmvnrepo",
    "module": "test-publish",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "test-publish-mingwX64Main-0.0.1.klib",
          "url": "test-publish-mingwx64-0.0.1.klib",
          "size": 3051,
          "sha512": "4f5930e2c2e785da1b38298dfb0db5ee9c0390c2d03a35301e0c795888517b919649c8e62949ed23f7d005afc21efbbd7f27d14cc7bd13f34ae092479d1e4985",
          "sha256": "eebecec6cdc72388696300ec8c19ea17d9dc0ec308cccb60621f2e1d874cebde",
          "sha1": "ed200abb86053a31f3d386c68643a78a42c6a58a",
          "md5": "5cf98bc7c0472c23c042ee24b3da5b5a"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-publish-mingwx64-0.0.1-sources.jar",
          "url": "test-publish-mingwx64-0.0.1-sources.jar",
          "size": 732,
          "sha512": "9aa4f139d0772973aa300c07a30655432e5c9822e0a9c7ead82441ca250be2c340b5aa7de203918a18db36092005ebe98b4961dc9d1d1e67d16eab95733794b3",
          "sha256": "c8c2bd42def53fbce3d593754acae20e876720c78d22739180fe2eab06375179",
          "sha1": "32f4399c0736653f36a759576fafc37342a458f1",
          "md5": "d96628c64e5df1af9bc80536fd5446e2"
        }
      ]
    }
  ]
}
