{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.rtast.kmvnrepo",
    "module": "test-publish",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "test-publish-metadata-0.0.1.jar",
          "url": "test-publish-0.0.1.jar",
          "size": 1971,
          "sha512": "0cd9b8fc40f55c93b00a73a2008eb6e583c872e5459282327557e064630e8e0e9b09246d5d0d6930e16a9d0c023d0d60f4701dc0a4965ecb312524f69cd4fff2",
          "sha256": "621206f460a33a888ec22ae7502a2b11593fdcbec20052032929807d222e6ac5",
          "sha1": "6aeace700739e650fa636210c4853d5fe398488a",
          "md5": "e649eb12e09cd33a11b90af1d87abfd8"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-publish-kotlin-0.0.1-sources.jar",
          "url": "test-publish-0.0.1-sources.jar",
          "size": 732,
          "sha512": "9aa4f139d0772973aa300c07a30655432e5c9822e0a9c7ead82441ca250be2c340b5aa7de203918a18db36092005ebe98b4961dc9d1d1e67d16eab95733794b3",
          "sha256": "c8c2bd42def53fbce3d593754acae20e876720c78d22739180fe2eab06375179",
          "sha1": "32f4399c0736653f36a759576fafc37342a458f1",
          "md5": "d96628c64e5df1af9bc80536fd5446e2"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-publish-jvm/0.0.1/test-publish-jvm-0.0.1.module",
        "group": "cn.rtast.kmvnrepo",
        "module": "test-publish-jvm",
        "version": "0.0.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-publish-jvm/0.0.1/test-publish-jvm-0.0.1.module",
        "group": "cn.rtast.kmvnrepo",
        "module": "test-publish-jvm",
        "version": "0.0.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-publish-jvm/0.0.1/test-publish-jvm-0.0.1.module",
        "group": "cn.rtast.kmvnrepo",
        "module": "test-publish-jvm",
        "version": "0.0.1"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-publish-mingwx64/0.0.1/test-publish-mingwx64-0.0.1.module",
        "group": "cn.rtast.kmvnrepo",
        "module": "test-publish-mingwx64",
        "version": "0.0.1"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-publish-mingwx64/0.0.1/test-publish-mingwx64-0.0.1.module",
        "group": "cn.rtast.kmvnrepo",
        "module": "test-publish-mingwx64",
        "version": "0.0.1"
      }
    }
  ]
}
